name: deployment CI/CD

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  deploy:
    name: client, server Deploy
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          timeout: 40s
          script: |
            echo "SSH 접속 완료"

            cd web15-Teleparty
            git pull
            npm install
            cd packages/frontend
            npm run build

            cd ../backend
            pm2 kill
            pm2 start src/app.ts

            cd ../socketServer
            pm2 start src/app.ts
